#!/usr/bin/env python3
"""
Generate bundled_credentials.py for release builds from environment variables.

Required for a full release bundle:
  TWITCH_CLIENT_ID, TWITCH_CLIENT_SECRET
  YOUTUBE_CLIENT_SECRETS_PATH (path to Google client_secrets.json)

Optional:
  PATREON_CLIENT_ID, PATREON_CLIENT_SECRET

Example:
  set TWITCH_CLIENT_ID=...
  set TWITCH_CLIENT_SECRET=...
  set YOUTUBE_CLIENT_SECRETS_PATH=C:\\path\\to\\client_secrets.json
  python scripts/generate_bundled_credentials.py

Use ``--allow-missing`` only for partial local experiments (not release builds).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "multistream_revenue_tracker" / "bundled_credentials.py"


def _env(name: str) -> str:
    return os.environ.get(name, "").strip()


def _load_youtube_config() -> dict | None:
    path = _env("YOUTUBE_CLIENT_SECRETS_PATH")
    if not path:
        return None
    p = Path(path)
    if not p.is_file():
        raise SystemExit(f"YOUTUBE_CLIENT_SECRETS_PATH not found: {p}")
    data = json.loads(p.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit("YouTube client secrets file must be a JSON object")
    return data


def _validate(*, allow_missing: bool, twitch_id: str, twitch_secret: str, youtube_config: dict | None) -> None:
    missing: list[str] = []
    if not twitch_id:
        missing.append("TWITCH_CLIENT_ID")
    if not twitch_secret:
        missing.append("TWITCH_CLIENT_SECRET")
    if youtube_config is None:
        missing.append("YOUTUBE_CLIENT_SECRETS_PATH (valid file)")

    if not missing:
        return

    message = "Missing required build credentials: " + ", ".join(missing)
    if not allow_missing:
        raise SystemExit(message)
    for item in missing:
        print(f"Warning: {item} not set", file=sys.stderr)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate bundled_credentials.py for release builds")
    parser.add_argument(
        "--allow-missing",
        action="store_true",
        help="Warn and continue if Twitch or YouTube credentials are missing (not for release builds)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUT,
        help="Path for bundled_credentials.py (default: package template location)",
    )
    parser.add_argument(
        "--check-empty",
        action="store_true",
        help=(
            "Exit non-zero if the committed bundled_credentials.py contains any non-empty "
            "client secrets. Run this in CI to prevent accidentally committing secrets."
        ),
    )
    args = parser.parse_args()

    if args.check_empty:
        return _check_empty(args.output)

    twitch_id = _env("TWITCH_CLIENT_ID")
    twitch_secret = _env("TWITCH_CLIENT_SECRET")
    patreon_id = _env("PATREON_CLIENT_ID")
    patreon_secret = _env("PATREON_SECRET") or _env("PATREON_CLIENT_SECRET")
    youtube_config = _load_youtube_config()

    _validate(allow_missing=args.allow_missing, twitch_id=twitch_id, twitch_secret=twitch_secret, youtube_config=youtube_config)

    youtube_repr = repr(youtube_config)
    content = f'''"""
Developer-application credentials bundled at release build time.

Generated by scripts/generate_bundled_credentials.py — do not edit by hand.
"""

from __future__ import annotations

from typing import Any

TWITCH_CLIENT_ID: str = {twitch_id!r}
TWITCH_CLIENT_SECRET: str = {twitch_secret!r}
PATREON_CLIENT_ID: str = {patreon_id!r}
PATREON_CLIENT_SECRET: str = {patreon_secret!r}
YOUTUBE_OAUTH_CLIENT_CONFIG: dict[str, Any] | None = {youtube_repr}
'''
    args.output.write_text(content, encoding="utf-8")
    print(f"Wrote {args.output}")


def _check_empty(path: Path) -> None:
    """Fail if the repo's bundled_credentials.py contains any non-empty secret."""
    if not path.is_file():
        raise SystemExit(f"bundled_credentials.py not found: {path}")
    src = path.read_text(encoding="utf-8")
    offenders: list[str] = []
    empty_str = re.compile(r"^(?:''|\"\")$")
    for name in (
        "TWITCH_CLIENT_ID",
        "TWITCH_CLIENT_SECRET",
        "PATREON_CLIENT_ID",
        "PATREON_CLIENT_SECRET",
    ):
        match = re.search(rf"^{re.escape(name)}:\s*str\s*=\s*(\S+)", src, re.MULTILINE)
        if not match or not empty_str.match(match.group(1)):
            offenders.append(name)
    if "YOUTUBE_OAUTH_CLIENT_CONFIG: dict[str, Any] | None = None" not in src:
        offenders.append("YOUTUBE_OAUTH_CLIENT_CONFIG")
    if offenders:
        raise SystemExit(
            "bundled_credentials.py has filled values for: "
            + ", ".join(offenders)
            + ". Restore the empty template before committing."
        )
    print(f"OK: {path} contains empty placeholders")


if __name__ == "__main__":
    main()
